// This file was generated by generator.py

#include "functions.hpp"

#include "org_duckdb_DuckDBNative.h"

#include <exception>

JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1startup(JNIEnv *env, jclass param0,
                                                                             jbyteArray param1, jboolean param2,
                                                                             jobject param3) {
	try {
		return _duckdb_jdbc_startup(env, param0, param1, param2, param3);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1connect(JNIEnv *env, jclass param0,
                                                                             jobject param1) {
	try {
		return _duckdb_jdbc_connect(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1create_1db_1ref(JNIEnv *env, jclass param0,
                                                                                     jobject param1) {
	try {
		return _duckdb_jdbc_create_db_ref(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1destroy_1db_1ref(JNIEnv *env, jclass param0,
                                                                                   jobject param1) {
	try {
		return _duckdb_jdbc_destroy_db_ref(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1set_1auto_1commit(JNIEnv *env, jclass param0,
                                                                                    jobject param1, jboolean param2) {
	try {
		return _duckdb_jdbc_set_auto_commit(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT jboolean JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1get_1auto_1commit(JNIEnv *env, jclass param0,
                                                                                        jobject param1) {
	try {
		return _duckdb_jdbc_get_auto_commit(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return false;
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1disconnect(JNIEnv *env, jclass param0,
                                                                             jobject param1) {
	try {
		return _duckdb_jdbc_disconnect(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1set_1schema(JNIEnv *env, jclass param0,
                                                                              jobject param1, jstring param2) {
	try {
		return _duckdb_jdbc_set_schema(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1set_1catalog(JNIEnv *env, jclass param0,
                                                                               jobject param1, jstring param2) {
	try {
		return _duckdb_jdbc_set_catalog(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT jstring JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1get_1schema(JNIEnv *env, jclass param0,
                                                                                 jobject param1) {
	try {
		return _duckdb_jdbc_get_schema(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT jstring JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1get_1catalog(JNIEnv *env, jclass param0,
                                                                                  jobject param1) {
	try {
		return _duckdb_jdbc_get_catalog(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1prepare(JNIEnv *env, jclass param0, jobject param1,
                                                                             jbyteArray param2) {
	try {
		return _duckdb_jdbc_prepare(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1pending_1query(JNIEnv *env, jclass param0,
                                                                                    jobject param1, jbyteArray param2) {
	try {
		return _duckdb_jdbc_pending_query(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1release(JNIEnv *env, jclass param0, jobject param1) {
	try {
		return _duckdb_jdbc_release(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1release_1pending(JNIEnv *env, jclass param0,
                                                                                   jobject param1) {
	try {
		_duckdb_jdbc_release_pending(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1query_1result_1meta(JNIEnv *env, jclass param0,
                                                                                         jobject param1) {
	try {
		return _duckdb_jdbc_query_result_meta(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1prepared_1statement_1meta(JNIEnv *env,
                                                                                               jclass param0,
                                                                                               jobject param1) {
	try {
		return _duckdb_jdbc_prepared_statement_meta(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1execute(JNIEnv *env, jclass param0, jobject param1,
                                                                             jobjectArray param2) {
	try {
		return _duckdb_jdbc_execute(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1execute_1pending(JNIEnv *env, jclass param0,
                                                                                      jobject param1) {
	try {
		return _duckdb_jdbc_execute_pending(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1free_1result(JNIEnv *env, jclass param0,
                                                                               jobject param1) {
	try {
		return _duckdb_jdbc_free_result(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT jobjectArray JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1fetch(JNIEnv *env, jclass param0,
                                                                                jobject param1, jobject param2) {
	try {
		return _duckdb_jdbc_fetch(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT jobjectArray JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1cast_1result_1to_1strings(
    JNIEnv *env, jclass param0, jobject param1, jobject param2, jlong param3) {
	try {
		return _duckdb_jdbc_cast_result_to_strings(env, param0, param1, param2, param3);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT jint JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1fetch_1size(JNIEnv *env, jclass param0) {
	try {
		return _duckdb_jdbc_fetch_size(env, param0);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return -1;
	}
}

JNIEXPORT jlong JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1arrow_1stream(JNIEnv *env, jclass param0,
                                                                                 jobject param1, jlong param2) {
	try {
		return _duckdb_jdbc_arrow_stream(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return -1;
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1arrow_1register(JNIEnv *env, jclass param0,
                                                                                  jobject param1, jlong param2,
                                                                                  jbyteArray param3) {
	try {
		return _duckdb_jdbc_arrow_register(env, param0, param1, param2, param3);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1create_1appender(JNIEnv *env, jclass param0,
                                                                                      jobject param1, jbyteArray param2,
                                                                                      jbyteArray param3) {
	try {
		return _duckdb_jdbc_create_appender(env, param0, param1, param2, param3);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1begin_1row(JNIEnv *env, jclass param0,
                                                                                       jobject param1) {
	try {
		return _duckdb_jdbc_appender_begin_row(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1end_1row(JNIEnv *env, jclass param0,
                                                                                     jobject param1) {
	try {
		return _duckdb_jdbc_appender_end_row(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1flush(JNIEnv *env, jclass param0,
                                                                                  jobject param1) {
	try {
		return _duckdb_jdbc_appender_flush(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1interrupt(JNIEnv *env, jclass param0,
                                                                            jobject param1) {
	try {
		return _duckdb_jdbc_interrupt(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1query_1progress(JNIEnv *env, jclass param0,
                                                                                     jobject param1) {
	try {
		return _duckdb_jdbc_query_progress(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
		return nullptr;
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1close(JNIEnv *env, jclass param0,
                                                                                  jobject param1) {
	try {
		return _duckdb_jdbc_appender_close(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1boolean(JNIEnv *env, jclass param0,
                                                                                            jobject param1,
                                                                                            jboolean param2) {
	try {
		return _duckdb_jdbc_appender_append_boolean(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1byte(JNIEnv *env, jclass param0,
                                                                                         jobject param1, jbyte param2) {
	try {
		return _duckdb_jdbc_appender_append_byte(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1short(JNIEnv *env, jclass param0,
                                                                                          jobject param1,
                                                                                          jshort param2) {
	try {
		return _duckdb_jdbc_appender_append_short(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1int(JNIEnv *env, jclass param0,
                                                                                        jobject param1, jint param2) {
	try {
		return _duckdb_jdbc_appender_append_int(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1long(JNIEnv *env, jclass param0,
                                                                                         jobject param1, jlong param2) {
	try {
		return _duckdb_jdbc_appender_append_long(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1float(JNIEnv *env, jclass param0,
                                                                                          jobject param1,
                                                                                          jfloat param2) {
	try {
		return _duckdb_jdbc_appender_append_float(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1double(JNIEnv *env, jclass param0,
                                                                                           jobject param1,
                                                                                           jdouble param2) {
	try {
		return _duckdb_jdbc_appender_append_double(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1string(JNIEnv *env, jclass param0,
                                                                                           jobject param1,
                                                                                           jbyteArray param2) {
	try {
		return _duckdb_jdbc_appender_append_string(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1bytes(JNIEnv *env, jclass param0,
                                                                                          jobject param1,
                                                                                          jbyteArray param2) {
	try {
		return _duckdb_jdbc_appender_append_bytes(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1timestamp(JNIEnv *env,
                                                                                              jclass param0,
                                                                                              jobject param1,
                                                                                              jlong param2) {
	try {
		return _duckdb_jdbc_appender_append_timestamp(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1decimal(JNIEnv *env, jclass param0,
                                                                                            jobject param1,
                                                                                            jobject param2) {
	try {
		return _duckdb_jdbc_appender_append_decimal(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1append_1null(JNIEnv *env, jclass param0,
                                                                                         jobject param1) {
	try {
		return _duckdb_jdbc_appender_append_null(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1create_1extension_1type(JNIEnv *env, jclass param0,
                                                                                          jobject param1) {
	try {
		return _duckdb_jdbc_create_extension_type(env, param0, param1);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT jstring JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1get_1profiling_1information(JNIEnv *env,
                                                                                                 jclass param0,
                                                                                                 jobject param1,
                                                                                                 jobject param2) {
	try {
		return _duckdb_jdbc_get_profiling_information(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());

		return nullptr;
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1register_1scalar_1udf(
    JNIEnv *env, jclass param0, jobject param1, jbyteArray param2, jobject param3, jobjectArray param4, jobject param5,
    jboolean param6, jboolean param7, jboolean param8, jboolean param9) {
	try {
		return _duckdb_jdbc_register_scalar_udf(env, param0, param1, param2, param3, param4, param5, param6, param7,
		                                        param8, param9);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1register_1table_1function(
    JNIEnv *env, jclass param0, jobject param1, jbyteArray param2, jobject param3, jobjectArray param4, jboolean param5,
    jint param6, jboolean param7) {
	try {
		return _duckdb_jdbc_register_table_function(env, param0, param1, param2, param3, param4, param5, param6,
		                                            param7);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT jbyteArray JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1udf_1get_1varchar_1bytes(JNIEnv *env,
                                                                                                 jclass param0,
                                                                                                 jobject param1,
                                                                                                 jint param2) {
	try {
		return _duckdb_jdbc_udf_get_varchar_bytes(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
		return nullptr;
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1udf_1set_1varchar_1bytes(JNIEnv *env, jclass param0,
                                                                                           jobject param1, jint param2,
                                                                                           jbyteArray param3) {
	try {
		return _duckdb_jdbc_udf_set_varchar_bytes(env, param0, param1, param2, param3);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT jbyteArray JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1udf_1get_1blob_1bytes(JNIEnv *env,
                                                                                              jclass param0,
                                                                                              jobject param1,
                                                                                              jint param2) {
	try {
		return _duckdb_jdbc_udf_get_blob_bytes(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
		return nullptr;
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1udf_1set_1blob_1bytes(JNIEnv *env, jclass param0,
                                                                                        jobject param1, jint param2,
                                                                                        jbyteArray param3) {
	try {
		return _duckdb_jdbc_udf_set_blob_bytes(env, param0, param1, param2, param3);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}

JNIEXPORT jobject JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1udf_1get_1decimal(JNIEnv *env, jclass param0,
                                                                                       jobject param1, jint param2) {
	try {
		return _duckdb_jdbc_udf_get_decimal(env, param0, param1, param2);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
		return nullptr;
	}
}

JNIEXPORT void JNICALL Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1udf_1set_1decimal(JNIEnv *env, jclass param0,
                                                                                    jobject param1, jint param2,
                                                                                    jobject param3) {
	try {
		return _duckdb_jdbc_udf_set_decimal(env, param0, param1, param2, param3);
	} catch (const std::exception &e) {
		duckdb::ErrorData error(e);
		ThrowJNI(env, error.Message().c_str());
	}
}
